openapi: 3.0.0
servers:
  - url: https://api.wiise.live
    description: Default server
paths:
  parameters:
    - name: x-functions-key
      description: dsd
      in: header
      example: "h0hsk8jNmap05Jkgjh93qpLmzlNfqPafdgit71kMnal0hfuqlaJqpa=="
      schema:
        type: string
  post:
    tags:
      - ChargeBee Webhook
    summary: Register new Tenant
    description: Testing resiterwiise
    operationId: addPet
    responses:
      "200":
        description: Success
      "401":
        description: Unauthorized acess
    x-code-samples:
      - lang: "HTTP"
        label: "HTTP Request"
        source: |
          POST /SubscritionCreated HTTP/1.1
          Host: https://web.wiise.live/SubscriptionCreated
          Content-Type: application/json; charset=utf-8
          Content-Length: 137

          {
            "status": "ok",
            "extended": true,
            "results": [
              {"value": 0, "type": "int64"},
              {"value": 1.0e+3, "type": "decimal"}
            ]
          }
      - lang: .Net
        label: ".Net"
        source: |
          private String createPet() throws JsonProcessingException {
            Pet pet = new Pet();
            pet.setId(1l);
            pet.setName("Wuffy");
            Category category = new Category(1l, "Hund");
            pet.setCategory(category);
            return new ObjectMapper().writeValueAsString(pet);
          }
    requestBody:
      $ref: "#/components/requestBodies/registerwiise"

components:
  schemas:
    registerWiise:
      description: Item existing in ChargeBee Subscription.
      type: object
      properties:
        tenantId:
          type: string
          description:
          example: 600f3cd7-b0f9-4b43-a01b-4e74a0aa3993
        applicationDomain:
          type: string
          description:
          example: 00
        environment:
          type: string
          description:
          example: 01
        environmentName:
          type: string
          description:
          example: WiiseTesting
        environmentId:
          type: string
          description:
          example: FB061173-28BB-476F-8C6A-08BB130A2276
        currWiiseApplicationVersion:
          type: string
          description:
          example: (Wiise AU 19.300.0.4)
        createNewKey:
          type: boolean
          description:
          example: true
  requestBodies:
    registerwiise:
      content:
        application/json:
          schema:
            allOf:
              - description: Adding a new Business License
                title: Pettie
              - $ref: "#/components/schemas/registerWiise"
      description: JSON for subscription that is released by ChargeBee upon Subscription Creation for a customer.
      required: true
